// Full 133-hero roster. Role(s) and tier reflect a patch 2.1.90 (Aug 2026) snapshot — refresh each patch.
// `details` (skills, build, emblem, matchups) is filled in gradually, hero by hero, researched from real kits —
// heroes without it yet show a "details coming soon" state in the UI rather than made-up data.
// Full current roster, role(s) and tier as of patch 2.1.90 (Aug 2026)
const HERO_META = [
  { name: "Aamon", roles: ["Assassin"], tier: "B" },
  { name: "Akai", roles: ["Tank"], tier: "B" },
  { name: "Aldous", roles: ["Fighter"], tier: "C" },
  { name: "Alice", roles: ["Tank", "Mage"], tier: "B" },
  { name: "Alpha", roles: ["Fighter"], tier: "C" },
  { name: "Alucard", roles: ["Fighter", "Assassin"], tier: "B" },
  { name: "Angela", roles: ["Support"], tier: "B" },
  { name: "Argus", roles: ["Fighter"], tier: "A" },
  { name: "Arlott", roles: ["Fighter", "Assassin"], tier: "C" },
  {
    name: "Atlas",
    roles: ["Tank"],
    tier: "S",
    details: {
      passive: { name: "Frigid Breath", desc: "Each skill Atlas casts leaves a cold aura around him briefly. Enemies who linger in it are slowed and eventually frozen in place, while Atlas gains bonus physical and magic defense for as long as the aura is up." },
      skills: [
        { name: "Annihilate", type: "Skill 1", desc: "Atlas slams the ground for three quick explosions of magic damage. If he's been ejected from his Mecha Sentry, both he and the Mecha unleash it together for double the area." },
        { name: "Perfect Match", type: "Skill 2 / Blink", desc: "Atlas dashes toward a target location, damaging and briefly disabling enemies he passes through. His main tool for closing distance before locking in a fight." },
        { name: "Fatal Links", type: "Ultimate", desc: "Atlas channels and drags every enemy hero in a large radius toward him, damaging and stunning them on arrival. Channeling longer increases the pull range, not the damage — so don't hold it longer than needed." },
      ],
      build: ["Warrior Boots", "Antique Cuirass", "Dominance Ice", "Athena's Shield", "Immortality", "Cursed Helmet"],
      emblem: { type: "Tank Emblem", talents: ["Agility", "Pull Yourself Together", "Focusing Mark"] },
      spell: "Flicker",
      strongAgainst: ["Ling", "Kimmy", "Masha", "Hanabi"],
      weakAgainst: ["Cecilion", "Karrie", "Granger", "Pharsa"],
      goodWith: ["Ling", "Fredrinn", "Valentina", "Natan"],
    },
  },
  { name: "Aulus", roles: ["Fighter"], tier: "B" },
  { name: "Aurora", roles: ["Mage"], tier: "C" },
  { name: "Badang", roles: ["Fighter"], tier: "B" },
  { name: "Balmond", roles: ["Fighter"], tier: "C" },
  { name: "Bane", roles: ["Fighter", "Mage"], tier: "B" },
  { name: "Barats", roles: ["Tank", "Fighter"], tier: "A" },
  { name: "Baxia", roles: ["Tank"], tier: "D" },
  {
    name: "Beatrix",
    roles: ["Marksman"],
    tier: "B",
    details: {
      passive: { name: "Mechanical Genius", desc: "Beatrix carries four different guns and can swap between two equipped at once. She can't land critical hits — instead, every point of crit chance she gains is converted straight into bonus physical attack." },
      skills: [
        { name: "Masterful Gunner", type: "Skill 1", desc: "Swap her active weapon between Renner (long-range poke), Wesker (shotgun burst), Nibiru (grenade launcher) and Bennett (heavy cannon) — each with its own basic attack and ultimate effect." },
        { name: "Tactical Reposition", type: "Skill 2 / Dash", desc: "Beatrix slides forward and fully reloads her current weapon, letting her reposition and reset her clip in one move." },
        { name: "Weapon Ultimate", type: "Ultimate", desc: "Fires a powerful shot unique to whichever gun is equipped — Renner pierces at long range, Wesker bursts up close, Nibiru bombs an area, and Bennett unloads a heavy volley." },
      ],
      build: ["Swift Boots", "Berserker's Fury", "Malefic Roar", "Windtalker", "Blade of Despair", "Immortality"],
      emblem: { type: "Assassin Emblem", talents: ["Rupture", "Weapons Master", "Killing Spree"] },
      spell: "Flicker",
      strongAgainst: ["Hylos", "Belerick", "immobile tanks without escape tools"],
      weakAgainst: ["Paquito", "Benedetta", "Yve", "Barats"],
      goodWith: ["Johnson", "Gloo", "Phoveus", "Aamon"],
    },
  },
  { name: "Belerick", roles: ["Tank"], tier: "S" },
  { name: "Benedetta", roles: ["Assassin", "Fighter"], tier: "A" },
  {
    name: "Brody",
    roles: ["Marksman"],
    tier: "B",
    details: {
      passive: { name: "Abyss Corrosion", desc: "Brody can move freely while winding up his basic attack, trading attack speed for mobility. Every basic attack or skill that lands stacks an Abyss Mark on the target, up to 4, each adding bonus damage and move speed." },
      skills: [
        { name: "Abyss Impact", type: "Skill 1 / AoE", desc: "Fires a shockwave that damages and slows enemies in a line — the more targets it passes through before the main target, the more marks it applies." },
        { name: "Corrosive Strike", type: "Skill 2 / Blink", desc: "Brody dashes forward, damaging enemies in his path — his main repositioning and engage tool." },
        { name: "Torn-Apart Memory", type: "Ultimate", desc: "A heavy burst attack that deals far more damage the more Abyss Marks are stacked on the target — best saved until a target is fully marked." },
      ],
      build: ["Warrior Boots", "Blade of the Heptaseas", "Malefic Roar", "Wind of Nature", "Sea Halberd", "Rose Gold Meteor"],
      emblem: { type: "Assassin Emblem", talents: ["Rupture", "Master Assassin", "Lethal Ignition"] },
      spell: "Flicker",
      strongAgainst: ["Isolated squishy targets caught without peel"],
      weakAgainst: ["Heavy CC compositions that stop mark stacking"],
      goodWith: ["Peel supports who protect his slow attack windup"],
    },
  },
  {
    name: "Bruno",
    roles: ["Marksman"],
    tier: "C",
    details: {
      passive: { name: "Mecha Legs", desc: "Bruno's skills convert into bonus critical chance rather than raw damage, so his power comes from stacking crit-scaling items rather than flat attack." },
      skills: [
        { name: "Volley Shot", type: "Skill 1", desc: "A curving kick that damages and slows the first enemy hit — his main poke and wave-clear tool." },
        { name: "Flying Tackle", type: "Skill 2 / Blink", desc: "Bruno dashes to a target, damaging and briefly disabling them — used to engage or reposition." },
        { name: "Worldie", type: "Ultimate", desc: "A long-range curving kick that deals heavy burst damage to the first hero hit, strong for picking off an overextended target." },
      ],
      build: ["Swift Boots", "Berserker's Fury", "Endless Battle", "Malefic Roar", "Wind of Nature", "Immortality"],
      emblem: { type: "Marksman Emblem", talents: ["Swift", "Weapons Master", "Bargain Hunter"] },
      spell: "Inspire",
      strongAgainst: ["Grouped, low-mobility lineups he can poke freely"],
      weakAgainst: ["Lesley", "Layla", "Barats"],
      goodWith: ["Tanks who can set up his Ultimate pick-off angle"],
    },
  },
  { name: "Carmilla", roles: ["Support", "Tank"], tier: "A" },
  { name: "Cecilion", roles: ["Mage"], tier: "B" },
  { name: "Chang'e", roles: ["Mage"], tier: "C" },
  { name: "Chip", roles: ["Support", "Tank"], tier: "C" },
  { name: "Chou", roles: ["Fighter"], tier: "C" },
  { name: "Cici", roles: ["Fighter"], tier: "C" },
  {
    name: "Claude",
    roles: ["Marksman"],
    tier: "C",
    details: {
      passive: { name: "Battle Side-by-Side", desc: "Claude fights alongside his partner Dexter, a mynah bird that mirrors his basic attacks — giving him effectively double damage output on autos." },
      skills: [
        { name: "Art of Thievery", type: "Skill 1 / AoE", desc: "Claude and Dexter dash through an area, damaging enemies and stealing physical attack and movement speed from each hero hit for a short time." },
        { name: "Battle Mirror Image", type: "Skill 2 / Blink", desc: "Claude and Dexter swap places, each dashing to the other's location — a strong dodge and repositioning tool, especially against skillshots." },
        { name: "Blazing Duet", type: "Ultimate", desc: "Claude and Dexter unleash a barrage of shots in an area, dealing heavy damage and shielding Claude based on stolen stats." },
      ],
      build: ["Swift Boots", "Scarlet Phantom", "Windtalker", "Berserker's Fury", "Malefic Roar", "Immortality"],
      emblem: { type: "Marksman Emblem", talents: ["Swift", "Bargain Hunter", "Weapons Master"] },
      spell: "Purify",
      strongAgainst: ["Lesley", "Bruno", "Edith"],
      weakAgainst: ["Hard engage assassins who can burst him before he stacks stolen stats"],
      goodWith: ["Frontline that can protect his setup phase"],
    },
  },
  {
    name: "Clint",
    roles: ["Marksman"],
    tier: "B",
    details: {
      passive: { name: "Double Shot", desc: "Clint's basic attacks fire two shots instead of one, giving him unusually high early burst for a marksman." },
      skills: [
        { name: "Quick Draw", type: "Skill 1", desc: "Clint fires an enhanced shot that deals bonus damage and briefly increases his attack speed — his core poke and trade tool." },
        { name: "Trapping Recoil", type: "Skill 2 / Blink", desc: "Clint backflips away while firing at enemies in front of him, giving him a built-in escape with damage attached." },
        { name: "Grenade Bombardment", type: "Ultimate", desc: "Clint throws a grenade that explodes into a wide area, damaging and slowing every enemy caught inside." },
      ],
      build: ["Swift Boots", "Endless Battle", "Scarlet Phantom", "Windtalker", "Malefic Roar", "Immortality"],
      emblem: { type: "Assassin Emblem", talents: ["Rupture", "Weapons Master", "Killing Spree"] },
      spell: "Flicker",
      strongAgainst: ["Nana", "Miya", "Aurora", "Moskov", "Alpha"],
      weakAgainst: ["Dive assassins who close the gap before Trapping Recoil is up"],
      goodWith: ["Roamers who can zone the enemy jungler off his lane"],
    },
  },
  { name: "Cyclops", roles: ["Mage"], tier: "B" },
  { name: "Diggie", roles: ["Support"], tier: "A" },
  { name: "Dyrroth", roles: ["Fighter"], tier: "B" },
  {
    name: "Edith",
    roles: ["Tank", "Marksman"],
    tier: "B",
    details: {
      passive: { name: "Iron Legion", desc: "Edith fights inside her mech, Phylax. Every point of extra physical and magic defense she buys converts into magic power while she's in Flight state, turning a pure tank build into real damage." },
      skills: [
        { name: "Earth Shatter", type: "Skill 1", desc: "After a short delay, Phylax slams the ground in a direction, dealing physical damage and knocking enemies airborne — regular crowd control can't interrupt the cast." },
        { name: "Onward, Phylax!", type: "Skill 2 / Dash", desc: "Edith launches Phylax forward, damaging and pulling enemies caught in its path toward her." },
        { name: "Primal Wrath", type: "Ultimate / Morph", desc: "Edith ejects from Phylax into Flight state, gaining massive attack speed and magic lifesteal based on stacked Wrath — her damage-dealing burst window." },
      ],
      build: ["Tough Boots", "Dominance Ice", "Antique Cuirass", "Athena's Shield", "Brute Force Breastplate", "Immortality"],
      emblem: { type: "Tank Emblem", talents: ["Swift", "Tenacity", "Quantum Charge"] },
      spell: "Flicker",
      strongAgainst: ["Squishy backline once Flight state closes distance"],
      weakAgainst: ["Burst mages who punish her before Wrath stacks up"],
      goodWith: ["Damage dealers who can follow up on her airborne knock-up"],
    },
  },
  { name: "Esmeralda", roles: ["Tank", "Mage"], tier: "B" },
  { name: "Estes", roles: ["Support"], tier: "A" },
  { name: "Eudora", roles: ["Mage"], tier: "A" },
  { name: "Fanny", roles: ["Assassin"], tier: "D" },
  { name: "Faramis", roles: ["Support", "Mage"], tier: "B" },
  { name: "Floryn", roles: ["Support"], tier: "S" },
  { name: "Franco", roles: ["Tank"], tier: "D" },
  { name: "Fredrinn", roles: ["Fighter", "Tank"], tier: "A" },
  { name: "Freya", roles: ["Fighter"], tier: "C" },
  { name: "Gatotkaca", roles: ["Tank", "Fighter"], tier: "D" },
  {
    name: "Gloo",
    roles: ["Tank"],
    tier: "S",
    details: {
      passive: { name: "Stick, Stick", desc: "Enemies hit by Gloo's skills gain stacks of Sticky, which slows them and reduces the damage they deal to him. Stacking this up before committing is the core of playing Gloo well." },
      skills: [
        { name: "Slam, Slam", type: "Skill 1 / AoE", desc: "Gloo drops a puddle of goo at range that damages enemies on impact. He can walk through his own puddle to refund part of the cooldown and heal." },
        { name: "Pass, Pass", type: "Skill 2 / CC", desc: "A wave of smaller goo blobs fans out; if it connects with a puddle he's already placed, Gloo dashes to it and drags enemies caught in the way." },
        { name: "Split, Split", type: "Skill 3", desc: "Gloo splits into a decoy, letting him bait skills or scout safely while the real Gloo repositions." },
        { name: "Go With The Flow", type: "Ultimate", desc: "Gloo attaches to a target enemy hero, transferring most damage he takes back onto them for the duration — turning him into a walking damage trap for whoever he's stuck to." },
      ],
      build: ["Tough Boots", "Cursed Helmet", "Thunder Belt", "Oracle", "Dominance Ice", "Immortality"],
      emblem: { type: "Tank Emblem", talents: ["Agility", "Tenacity", "Brave Smite"] },
      spell: "Flicker",
      strongAgainst: ["Squishy backline mages/marksmen once attached"],
      weakAgainst: ["Faramis", "true damage dealers"],
      goodWith: ["Burst damage dealers who can follow up on his attach"],
    },
  },
  { name: "Gord", roles: ["Mage"], tier: "S" },
  {
    name: "Granger",
    roles: ["Marksman"],
    tier: "D",
    details: {
      passive: { name: "Capriccio", desc: "Granger's gun and cannon share a Demonic Energy pool instead of mana — each auto-attack fires from a 6-round clip that reloads on its own, and his cooldown reduction stat also boosts his physical attack directly." },
      skills: [
        { name: "Rhapsody", type: "Skill 1 / Burst", desc: "Granger fires a spinning shot in a line, dealing burst physical damage to everyone it passes through — his main poke and finishing tool, with no travel-time delay." },
        { name: "Rondo", type: "Skill 2 / Blink", desc: "Granger dashes in a direction, gaining bonus movement speed — his only mobility tool, so it doubles as his engage and escape." },
        { name: "Death Sonata", type: "Ultimate", desc: "Granger switches to his cannon for a set number of shots, each dealing heavy AoE physical damage — best unleashed once his gun clip is already spent." },
      ],
      build: ["Swift Boots", "Hunter Strike", "Sky Piercer", "Malefic Roar", "Blade of Despair", "Immortality"],
      emblem: { type: "Assassin Emblem", talents: ["Thrill", "Festival of Blood", "Lethal Ignition"] },
      spell: "Flicker",
      strongAgainst: ["Khufra", "Hanabi", "Esmeralda", "Kimmy"],
      weakAgainst: ["Guinevere", "Minsitthar", "Helcurt", "Selena", "Gusion"],
      goodWith: ["Carmilla", "Dyrroth", "Lylia"],
    },
  },
  { name: "Grock", roles: ["Tank", "Fighter"], tier: "C" },
  { name: "Guinevere", roles: ["Fighter"], tier: "A" },
  { name: "Gusion", roles: ["Assassin"], tier: "B" },
  {
    name: "Hanabi",
    roles: ["Marksman"],
    tier: "B",
    details: {
      passive: { name: "Petal Barrage", desc: "Hanabi's basic attacks and skills fire Petal Blades that bounce to nearby enemies, so her damage scales up sharply when enemies group together." },
      skills: [
        { name: "Ninjutsu: Equinox", type: "Skill 1", desc: "Hanabi throws a scroll that damages and slows the enemy wave, restoring mana on hit — the setup for everything else in her kit." },
        { name: "Ninjutsu: Soul Scroll", type: "Skill 2", desc: "Marks an area, boosting Hanabi's damage against anyone standing in it — rewards fighting on top of her mark." },
        { name: "Forbidden Jutsu: Higanbana", type: "Ultimate", desc: "Throws a flower that blooms on impact, immobilizing and damaging the target, then blooms again if more enemies are nearby — can chain across a grouped enemy team." },
      ],
      build: ["Swift Boots", "Corrosion Scythe", "Demon Hunter Sword", "Golden Staff", "Sea Halberd", "Rose Gold Meteor"],
      emblem: { type: "Marksman Emblem", talents: ["Swift", "Weapons Master", "Weakness Finder"] },
      spell: "Purify",
      strongAgainst: ["Grouped teamfight compositions"],
      weakAgainst: ["Bruno", "Beatrix", "Irithel", "hard dive assassins (no built-in dash)"],
      goodWith: ["Frontline that can hold space so her damage ramps up safely"],
    },
  },
  { name: "Hanzo", roles: ["Assassin"], tier: "A" },
  { name: "Harith", roles: ["Mage"], tier: "D" },
  { name: "Harley", roles: ["Assassin", "Mage"], tier: "C" },
  { name: "Hayabusa", roles: ["Assassin"], tier: "C" },
  { name: "Helcurt", roles: ["Assassin"], tier: "B" },
  { name: "Hilda", roles: ["Fighter", "Tank"], tier: "A" },
  { name: "Hirara", roles: ["Assassin"], tier: "A" },
  { name: "Hylos", roles: ["Tank"], tier: "C" },
  {
    name: "Irithel",
    roles: ["Marksman"],
    tier: "A",
    details: {
      passive: { name: "Companion: Leo", desc: "Irithel fights alongside her smilodon Leo, letting her fire basic attacks — several crossbow bolts per shot — while moving, unlike most marksmen who must stand still to auto-attack." },
      skills: [
        { name: "Strafe", type: "Skill 1", desc: "Irithel fires a volley into a fixed-range target area, damaging enemies and reducing their physical defense — usually maxed first to boost her sustained damage." },
        { name: "Heavy Crossbow", type: "Skill 2 / AoE", desc: "Fires a wave of bolts in a cone, damaging and slowing enemies hit — good for both poke and chasing." },
        { name: "Rain of Judgement", type: "Ultimate", desc: "Irithel leaps into the air and rains bolts down on an area below, dealing heavy repeated damage to anyone caught inside." },
      ],
      build: ["Swift Boots", "Demon Hunter Sword", "Corrosion Scythe", "Scarlet Phantom", "Malefic Roar", "Immortality"],
      emblem: { type: "Assassin Emblem", talents: ["Fatal", "Master Assassin", "Quantum Charge"] },
      spell: "Flicker",
      strongAgainst: ["Tanks (armor-shred from Strafe), immobile frontlines"],
      weakAgainst: ["Hayabusa", "Lancelot", "Ling", "Gusion"],
      goodWith: ["Peel-heavy teams that protect her fixed-range positioning"],
    },
  },
  {
    name: "Ixia",
    roles: ["Marksman"],
    tier: "C",
    details: {
      passive: { name: "Siphon Starlium", desc: "Landing basic attacks and skills builds stacks; at max stacks, Ixia's next basic attack unleashes a bonus burst of damage and heals her — rewarding weaving autos between every skill." },
      skills: [
        { name: "Dual Beam", type: "Skill 1", desc: "Fires twin beams that damage enemies and grant Ixia bonus attack speed for a few seconds, generating stacks toward her passive." },
        { name: "Star Helix", type: "Skill 2 / CC", desc: "Ixia fires a spiraling projectile that slows enemies it passes through — her main zoning and control tool." },
        { name: "Full Barrage", type: "Ultimate", desc: "Ixia creates a wide frontal firing zone that boosts her damage and lets her attack multiple enemies at once — she acts as her own initiator in teamfights, unlike most marksmen." },
      ],
      build: ["Swift Boots", "Corrosion Scythe", "Demon Hunter Sword", "Windtalker", "Malefic Roar", "Immortality"],
      emblem: { type: "Marksman Emblem", talents: ["Swift", "Weapons Master", "Bargain Hunter"] },
      spell: "Inspire",
      strongAgainst: ["Tigreal", "Fredrinn", "Bane", "static front-to-back lineups"],
      weakAgainst: ["Ling", "Saber", "Aamon", "flanking dive comps"],
      goodWith: ["Vexana", "Atlas", "Zilong", "Chou"],
    },
  },
  { name: "Jawhead", roles: ["Fighter"], tier: "C" },
  { name: "Johnson", roles: ["Tank", "Support"], tier: "B" },
  { name: "Joy", roles: ["Assassin"], tier: "C" },
  { name: "Julian", roles: ["Assassin", "Fighter"], tier: "B" },
  { name: "Kadita", roles: ["Mage", "Assassin"], tier: "A" },
  { name: "Kagura", roles: ["Mage"], tier: "B" },
  { name: "Kaja", roles: ["Support"], tier: "C" },
  { name: "Kalea", roles: ["Support", "Fighter"], tier: "D" },
  { name: "Karina", roles: ["Assassin"], tier: "D" },
  {
    name: "Karrie",
    roles: ["Marksman"],
    tier: "C",
    details: {
      passive: { name: "True Damage Conversion", desc: "A portion of Karrie's physical attack against heroes is converted into true damage, letting her partially bypass armor stacking." },
      skills: [
        { name: "Zephyr Wings", type: "Skill 1 / Dash", desc: "Karrie dashes through an enemy, damaging them and gaining bonus attack speed for a few seconds." },
        { name: "Twin Blast", type: "Skill 2", desc: "Karrie's attacks pierce through her target to hit an enemy behind them, useful for hitting backline through a frontline body." },
        { name: "Where Are You?!", type: "Ultimate", desc: "Karrie fires a tracking arrow that briefly disarms a target hero's basic attacks and lets her see them through fog of war." },
      ],
      build: ["Swift Boots", "Demon Hunter Sword", "Berserker's Fury", "Windtalker", "Malefic Roar", "Immortality"],
      emblem: { type: "Assassin Emblem", talents: ["Fatal", "Master Assassin", "Killing Spree"] },
      spell: "Flicker",
      strongAgainst: ["Heavily-armored frontline tanks she can pierce through"],
      weakAgainst: ["Burst assassins who kill her before she stacks attack speed"],
      goodWith: ["Frontline that groups enemies for her Twin Blast pierce"],
    },
  },
  { name: "Khaleed", roles: ["Fighter"], tier: "B" },
  { name: "Khufra", roles: ["Tank"], tier: "S" },
  {
    name: "Kimmy",
    roles: ["Marksman", "Mage"],
    tier: "C",
    details: {
      passive: { name: "Chemist's Instinct", desc: "Kimmy can move freely while firing her basic attacks, which are treated as skill shots and deal magic damage — she plays and itemizes like a hybrid mage-marksman rather than a standard auto-attacker." },
      skills: [
        { name: "Energy Transformation", type: "Skill 1 / AoE", desc: "Kimmy's basic attacks briefly become a wide beam that hits multiple enemies — strong for wave clear and poking grouped lanes." },
        { name: "Chemical Refinement", type: "Skill 2", desc: "Kimmy vaults over terrain and gains bonus magic penetration for a duration, helping her kite over walls other marksmen can't cross." },
        { name: "Maximum Charge", type: "Ultimate / Burst", desc: "Kimmy charges a powerful shot that deals heavy magic damage to the first enemy hit at long range — her main pick and finishing tool." },
      ],
      build: ["Arcane Boots", "Feather of Heaven", "Concentrated Energy", "Blood Wings", "Divine Glaive", "Holy Crystal"],
      emblem: { type: "Mage Emblem", talents: ["Agility", "Mystery Shop", "Lethal Ignition"] },
      spell: "Purify",
      strongAgainst: ["Valir", "Minotaur", "Moskov", "Vale", "Hylos"],
      weakAgainst: ["Gusion", "Aldous", "Lancelot", "Lolita", "Hayabusa"],
      goodWith: ["Yu Zhong", "Lancelot", "Kagura", "Rafaela"],
    },
  },
  { name: "Lancelot", roles: ["Assassin"], tier: "D" },
  { name: "Lapu-Lapu", roles: ["Fighter"], tier: "C" },
  {
    name: "Layla",
    roles: ["Marksman"],
    tier: "C",
    details: {
      passive: { name: "Malefic Gun", desc: "Layla deals bonus damage to enemies the farther away she is from them (excluding turrets) — rewarding max-range poking over close trades." },
      skills: [
        { name: "Malefic Bomb", type: "Skill 1", desc: "Fires a bomb in a line that deals physical damage and can critically strike — her main poke tool." },
        { name: "Void Projectile", type: "Skill 2", desc: "Fires a beam that damages and briefly slows every enemy it passes through." },
        { name: "Destruction Rain", type: "Ultimate", desc: "Layla fires a barrage of energy shots at a target area over several seconds, dealing heavy sustained damage to anyone who stays inside." },
      ],
      build: ["Swift Boots", "Endless Battle", "Scarlet Phantom", "Windtalker", "Malefic Roar", "Immortality"],
      emblem: { type: "Marksman Emblem", talents: ["Swift", "Weakness Finder", "Quantum Charge"] },
      spell: "Inspire",
      strongAgainst: ["Slow, low-mobility lanes she can out-range"],
      weakAgainst: ["Dive assassins (no dash or blink in her kit)"],
      goodWith: ["Roamers who can zone enemies out of her max-range comfort zone"],
    },
  },
  { name: "Leomord", roles: ["Fighter"], tier: "B" },
  {
    name: "Lesley",
    roles: ["Marksman", "Assassin"],
    tier: "C",
    details: {
      passive: { name: "Master Sniper", desc: "If Lesley avoids taking damage for a few seconds, her next basic attack gains extended range, guaranteed critical chance, and deals true damage — rewarding a hit-and-hide playstyle." },
      skills: [
        { name: "Leg Day", type: "Skill 1 / Dash", desc: "Lesley backflips away while firing at enemies in front of her — a built-in escape that keeps her passive's 'undamaged' timer alive." },
        { name: "Ace of Blast", type: "Skill 2 / Stealth", desc: "Lesley throws smoke bombs that damage enemies and grant her brief stealth, letting her reposition unseen." },
        { name: "Master Sniper", type: "Ultimate", desc: "Fires a long-range channeled shot that deals massive damage to the first hero hit, ideal for finishing grouped enemies from a safe distance." },
      ],
      build: ["Swift Boots", "Berserker's Fury", "Scarlet Phantom", "Windtalker", "Malefic Roar", "Immortality"],
      emblem: { type: "Marksman Emblem", talents: ["Fatal", "Weapons Master", "Quantum Charge"] },
      spell: "Flicker",
      strongAgainst: ["Miya", "clustered enemies in teamfights (Ultimate)"],
      weakAgainst: ["Dive assassins who close distance before her passive resets"],
      goodWith: ["Vision-control supports who help her stay hidden between fights"],
    },
  },
  { name: "Ling", roles: ["Assassin"], tier: "A" },
  { name: "Lolita", roles: ["Support", "Tank"], tier: "A" },
  { name: "Lukas", roles: ["Fighter"], tier: "A" },
  { name: "Lunox", roles: ["Mage"], tier: "C" },
  { name: "Luo Yi", roles: ["Mage"], tier: "D" },
  { name: "Lylia", roles: ["Mage"], tier: "C" },
  { name: "Marcel", roles: ["Support"], tier: "S" },
  { name: "Martis", roles: ["Fighter"], tier: "C" },
  { name: "Masha", roles: ["Fighter", "Tank"], tier: "S" },
  { name: "Mathilda", roles: ["Support", "Assassin"], tier: "D" },
  {
    name: "Melissa",
    roles: ["Marksman"],
    tier: "S",
    details: {
      passive: { name: "Doll Buster", desc: "Melissa deals bonus damage to minions, creeps, and summoned units — including her own puppet Muddles — making her a strong wave clearer and a hard counter to summon-reliant heroes." },
      skills: [
        { name: "Falling!", type: "Skill 1 / Blink", desc: "Melissa dashes a short distance and gains bonus attack speed. Its cooldown shortens further whenever she damages an enemy linked by Muddles — her core repositioning and DPS tool." },
        { name: "Eyes on You!", type: "Skill 2 / AoE", desc: "Melissa throws out her puppet Muddles, linking and slowing nearby enemies. Attacking Muddles directly hits every linked enemy at once for extra damage." },
        { name: "Go Away!", type: "Ultimate", desc: "Melissa summons Cuddles, which knocks enemies back and shields her while continuously damaging anyone caught inside — a strong panic button against dive assassins." },
      ],
      build: ["Swift Boots", "Corrosion Scythe", "Demon Hunter Sword", "Golden Staff", "Malefic Roar", "Immortality"],
      emblem: { type: "Marksman Emblem", talents: ["Swift", "Weapon Master", "Quantum Charge"] },
      spell: "Inspire",
      strongAgainst: ["Summon-reliant heroes (Sun, Popol and Kupa, Zhask)"],
      weakAgainst: ["Heavy burst assassins who close the gap before Falling! resets"],
      goodWith: ["Peel-heavy supports and tanks who can protect her backline position"],
    },
  },
  { name: "Minotaur", roles: ["Tank", "Support"], tier: "S" },
  { name: "Minsitthar", roles: ["Fighter"], tier: "A" },
  {
    name: "Miya",
    roles: ["Marksman"],
    tier: "A",
    details: {
      passive: { name: "Rising Moon", desc: "Each basic attack that hits a target grants Miya a stacking burst of attack speed for a few seconds, letting her ramp up DPS fast in extended fights." },
      skills: [
        { name: "Moon Arrow", type: "Skill 1 / AoE", desc: "Miya's next several basic attacks fire multiple arrows that hit all nearby enemies — key for wave clear and teamfight damage." },
        { name: "Turbo!", type: "Skill 2", desc: "Boosts Miya's attack speed for a duration, letting her stack Rising Moon faster." },
        { name: "Hidden Moonlight", type: "Ultimate", desc: "Miya turns invisible and gains bonus movement speed, usable both to initiate an ambush or to escape a losing fight." },
      ],
      build: ["Swift Boots", "Berserker's Fury", "Windtalker", "Scarlet Phantom", "Malefic Roar", "Immortality"],
      emblem: { type: "Marksman Emblem", talents: ["Fatal", "Weapons Master", "Bargain Hunter"] },
      spell: "Inspire",
      strongAgainst: ["Long teamfights where attack-speed stacking pays off"],
      weakAgainst: ["Natalia", "Hayabusa", "Karina", "Fanny"],
      goodWith: ["Frontline that shields her from dive until she's stacked up"],
    },
  },
  {
    name: "Moskov",
    roles: ["Marksman"],
    tier: "B",
    details: {
      passive: { name: "Spear of Quiescence", desc: "Moskov's basic attacks pierce through the first enemy hit, dealing reduced damage to whoever's standing behind them — rewarding him for lining up multiple targets." },
      skills: [
        { name: "Abyssal Spear", type: "Skill 1 / Blink", desc: "Moskov blinks toward a target direction and gains bonus attack speed for a few seconds — his main mobility and engage tool." },
        { name: "Spear of Misery", type: "Skill 2", desc: "Knocks an enemy back, and stuns them instead if they hit a wall or another hero behind them." },
        { name: "Spear of Destruction", type: "Ultimate", desc: "Throws a piercing spear that damages and slows everything in its path; using it again lets Moskov blink to the target for a follow-up hit." },
      ],
      build: ["Swift Boots", "Endless Battle", "Windtalker", "Scarlet Phantom", "Malefic Roar", "Immortality"],
      emblem: { type: "Marksman Emblem", talents: ["Fatal", "Weapons Master", "Quantum Charge"] },
      spell: "Flicker",
      strongAgainst: ["Grouped enemies his spear can pierce through"],
      weakAgainst: ["Fast burst assassins who close the gap before his blink is up"],
      goodWith: ["Tanks who line enemies up for his piercing Ultimate"],
    },
  },
  { name: "Nana", roles: ["Mage"], tier: "C" },
  { name: "Natalia", roles: ["Assassin"], tier: "B" },
  {
    name: "Natan",
    roles: ["Marksman"],
    tier: "B",
    details: {
      passive: { name: "Theory of Everything", desc: "Natan's basic attack projectiles travel forward then return to him, dealing bonus magic damage on the way back. Hitting enemies with his skills grants stacks that boost his attack and movement speed." },
      skills: [
        { name: "Superposition", type: "Skill 1", desc: "Natan fires a dense burst of energy in a line, dealing magic damage and building toward his passive's max stacks — his primary damage and wave-clear tool." },
        { name: "Interference!", type: "Skill 2", desc: "Places a reverse-clone that mirrors Natan's basic attacks from another angle, letting him hit enemies from two directions at once." },
        { name: "Entropy?", type: "Ultimate", desc: "Natan swaps places with his clone, letting him reposition instantly — usable both offensively to flank or defensively to escape a bad fight." },
      ],
      build: ["Arcane Boots", "Feather of Heaven", "Starlium Scythe", "Genius Wand", "Divine Glaive", "Holy Crystal"],
      emblem: { type: "Mage Emblem", talents: ["Agility", "Observation", "Impure Rage"] },
      spell: "Inspire",
      strongAgainst: ["Barats", "Tigreal", "Minotaur", "tanky frontlines he can shred with magic pen"],
      weakAgainst: ["Hayabusa", "Lancelot", "assassins who punish his low defense before he stacks"],
      goodWith: ["Peel-heavy tanks and supports who protect his stacking phase"],
    },
  },
  { name: "Nolan", roles: ["Assassin"], tier: "C" },
  { name: "Novaria", roles: ["Mage"], tier: "C" },
  {
    name: "Obsidia",
    roles: ["Marksman"],
    tier: "C",
    details: {
      passive: { name: "Return to Bone", desc: "Obsidia builds Bone Energy from dealing damage; once enough accumulates she gains a Bone Shard (up to 25). Every basic attack fires all her stored shards at the target for bonus damage, and killing a hero grants an instant shard." },
      skills: [
        { name: "Abyssal Bone Needle", type: "Skill 1 / AoE", desc: "Launches a piercing needle that damages enemies in a line and triggers her passive on the first hero hit." },
        { name: "Phantom Shadowmeld", type: "Skill 2", desc: "Obsidia briefly gains a massive burst of movement speed, letting her reposition or chase down a target fast." },
        { name: "Hunt of Bone", type: "Ultimate", desc: "Fires a bone spear that damages the first hero hit and pulls Obsidia toward them — a gap-closer that sets up a full shard unload." },
      ],
      build: ["Swift Boots", "Berserker's Fury", "Windtalker", "Scarlet Phantom", "Malefic Roar", "Immortality"],
      emblem: { type: "Marksman Emblem", talents: ["Swift", "Weapons Master", "Weakness Finder"] },
      spell: "Flicker",
      strongAgainst: ["Long fights where her Bone Shard stacks fully accumulate"],
      weakAgainst: ["Chou", "Guinevere", "Saber", "Fanny", "Ling"],
      goodWith: ["Frontline that buys her time to stack Bone Energy safely"],
    },
  },
  { name: "Odette", roles: ["Mage"], tier: "B" },
  { name: "Paquito", roles: ["Fighter", "Assassin"], tier: "A" },
  { name: "Pharsa", roles: ["Mage"], tier: "D" },
  { name: "Phoveus", roles: ["Fighter"], tier: "C" },
  {
    name: "Popol and Kupa",
    roles: ["Marksman"],
    tier: "A",
    details: {
      passive: { name: "Best Partner", desc: "Popol fights alongside his wolf companion Kupa, who inherits Popol's stats and attacks alongside him. If Kupa hasn't taken damage recently, Popol slowly heals him; if Kupa goes down, Popol must channel to summon him back." },
      skills: [
        { name: "Bite 'em, Kupa!", type: "Skill 1", desc: "Popol throws a spear at a target while ordering Kupa to bite them — both deal physical damage, with follow-up bites if Kupa is close." },
        { name: "Kupa, Help!", type: "Skill 2 / Trap", desc: "Places a trap that snares and damages the first enemy who steps on it — useful for zoning and vision control." },
        { name: "Alpha Wolf", type: "Ultimate", desc: "Kupa transforms into Alpha Wolf form, fully healing and gaining enhanced abilities and bonus movement speed for the duration." },
      ],
      build: ["Swift Boots", "Berserker's Fury", "Windtalker", "Scarlet Phantom", "Malefic Roar", "Immortality"],
      emblem: { type: "Marksman Emblem", talents: ["Swift", "Weapons Master", "Bargain Hunter"] },
      spell: "Flicker",
      strongAgainst: ["Static lanes where his traps can zone effectively"],
      weakAgainst: ["Burst dive that kills Kupa before he can be healed back up"],
      goodWith: ["Junglers who can capitalize on his trap-zoned targets"],
    },
  },
  { name: "Rafaela", roles: ["Support"], tier: "S" },
  {
    name: "Roger",
    roles: ["Fighter", "Marksman"],
    tier: "C",
    details: {
      passive: { name: "Werewolf Blood", desc: "Roger can freely switch between human form (ranged marksman, basic attacks slow enemies) and wolf form (melee fighter, gains defense and lifesteal) — effectively giving him two full skill sets in one hero." },
      skills: [
        { name: "Wolf Transformation", type: "Skill 1 / Morph", desc: "Switches Roger between human and wolf form, each with its own basic attack behavior and follow-up skills." },
        { name: "Open Fire / Bloodthirsty Howl", type: "Skill 2", desc: "In human form, fires a barrage of shots; in wolf form, howls to damage and briefly fear nearby enemies — the skill changes entirely based on his current form." },
        { name: "Lycan's Pounce", type: "Ultimate", desc: "Roger leaps to a target enemy, dealing damage and forcing wolf form on landing — his main gap-closer and form-switch initiator." },
      ],
      build: ["Swift Boots", "Sky Piercer", "Windtalker", "Endless Battle", "War Axe", "Malefic Roar"],
      emblem: { type: "Assassin Emblem", talents: ["Agility", "Seasoned Hunter", "Killing Spree"] },
      spell: "Retribution",
      strongAgainst: ["Sun", "Zilong", "Layla", "Lapu-Lapu"],
      weakAgainst: ["Karina", "Miya", "Aurora", "Alucard"],
      goodWith: ["Yve", "Mathilda", "Yu Zhong"],
    },
  },
  { name: "Ruby", roles: ["Fighter"], tier: "B" },
  { name: "Saber", roles: ["Assassin"], tier: "B" },
  { name: "Selena", roles: ["Assassin", "Mage"], tier: "C" },
  { name: "Silvanna", roles: ["Fighter"], tier: "A" },
  { name: "Sora", roles: ["Fighter", "Assassin"], tier: "B" },
  { name: "Sun", roles: ["Fighter"], tier: "S" },
  { name: "Suyou", roles: ["Assassin", "Fighter"], tier: "B" },
  { name: "Terizla", roles: ["Fighter", "Tank"], tier: "B" },
  { name: "Thamuz", roles: ["Fighter"], tier: "B" },
  { name: "Tigreal", roles: ["Tank"], tier: "C" },
  { name: "Uranus", roles: ["Tank"], tier: "B" },
  { name: "Vale", roles: ["Mage"], tier: "B" },
  { name: "Valentina", roles: ["Mage"], tier: "D" },
  { name: "Valir", roles: ["Mage"], tier: "A" },
  { name: "Vexana", roles: ["Mage"], tier: "B" },
  {
    name: "Wanwan",
    roles: ["Marksman"],
    tier: "C",
    details: {
      passive: { name: "Tiger Pace", desc: "Wanwan's movement speed scales with her attack speed, and every third basic attack dashes her behind the target — making attack-speed items double as mobility for her." },
      skills: [
        { name: "Swallow's Path", type: "Skill 1 / AoE, CC", desc: "Wanwan throws a dagger that marks a 'Weakness' on enemies hit; landing more hits on marked enemies ramps her attack and movement speed further." },
        { name: "Needles in Flowers", type: "Skill 2", desc: "Wanwan removes crowd control from herself and deals AoE damage around her — her main defensive and disengage tool." },
        { name: "Crossbow of Tang", type: "Ultimate", desc: "Wanwan fires a flurry of bolts at all nearby marked enemies, dealing massive damage and gaining crowd-control immunity while channeling." },
      ],
      build: ["Swift Boots", "Corrosion Scythe", "Demon Hunter Sword", "Windtalker", "Immortality", "Haas's Claws"],
      emblem: { type: "Marksman Emblem", talents: ["Fatal", "Weapons Master", "Weakness Finder"] },
      spell: "Inspire",
      strongAgainst: ["Granger", "Guinevere", "Harley", "Lesley"],
      weakAgainst: ["Ling", "Selena", "Lylia", "X.Borg", "Esmeralda"],
      goodWith: ["Julian", "Chang'e", "Angela", "Gusion"],
    },
  },
  { name: "X.Borg", roles: ["Fighter"], tier: "B" },
  { name: "Xavier", roles: ["Mage"], tier: "C" },
  {
    name: "Yi Sun-shin",
    roles: ["Assassin", "Marksman"],
    tier: "A",
    details: {
      passive: { name: "Glaive and Bow", desc: "Yi Sun-shin cycles between his glaive (melee) and bow (ranged) with every few basic attacks, each granting a different bonus effect — giving him both close-range and long-range tools in one kit." },
      skills: [
        { name: "Bramble Blade / Blazing Arrow", type: "Skill 1", desc: "Deals damage in melee (glaive) or a piercing shot at range (bow), depending on which weapon is currently active." },
        { name: "Air Combo / Flying Assault", type: "Skill 2 / Dash", desc: "Dashes toward an enemy for melee follow-up damage, or fires an area shot at range — his main gap-closer or poke tool depending on weapon state." },
        { name: "Mountain Shocker", type: "Ultimate / Global", desc: "Reveals a large area of the map and damages/slows enemies inside it — usable from anywhere, making him a strong map-pressure and pick tool." },
      ],
      build: ["Tough Boots", "War Axe", "Endless Battle", "Blade of Despair", "Malefic Roar", "Immortality"],
      emblem: { type: "Assassin Emblem", talents: ["Fatal", "Master Assassin", "Killing Spree"] },
      spell: "Retribution",
      strongAgainst: ["Squishy backline once he closes distance"],
      weakAgainst: ["Heroes with hard CC that punish his cycling combo"],
      goodWith: ["Selena", "Popol and Kupa"],
    },
  },
  { name: "Yin", roles: ["Fighter", "Assassin"], tier: "C" },
  { name: "Yu Zhong", roles: ["Fighter"], tier: "B" },
  { name: "Yve", roles: ["Mage"], tier: "B" },
  { name: "Zetian", roles: ["Mage"], tier: "A" },
  { name: "Zhask", roles: ["Mage"], tier: "B" },
  { name: "Zhuxin", roles: ["Mage"], tier: "C" },
  { name: "Zilong", roles: ["Fighter", "Assassin"], tier: "D" },
];

export { HERO_META };
export const TIER_ORDER = { S: 0, A: 1, B: 2, C: 3, D: 4 };
